In [21]:
#     NumPy Array Exercises

#  How to create an empty and a full NumPy array?

# python program to create
# Empty and Full Numpy arrays

import numpy as np


# Create an empty array
empa = np.empty((3, 4), dtype=int)
# print("Empty Array")
# print(empa)

# Create a full array
flla = np.full([3, 3], 55, dtype=int)
# print("\n Full Array")
# print(flla)

# Create a numpy array filled with zeros


# Python Program to create array with all zeros
import numpy as geek 
  
a=np.zeros([5,3])
# print(a)

# split non numeric values in array in numpy 
name= 'Masters in Data Science'
s= np.fromiter(name,dtype='U2')
# print(s)

linespace= np.linspace(3,12,3)
# print(linespace)

arr = np.ones(3)
print(arr)

[1. 1. 1.]


In [22]:
## We can create 2 dimentional arrays using 3 methods
# 1. np.diag(), 2. np.eye()

# np.eye is called numpy identity method which it returns the elements
# where i=j (row index and column index are equal)
# are 1 and the rest are 0, as such:

# print(np.eye(3))


print(np.diag())



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
#3 Finding maximum element from an matrix

#  we can use max() function which takes a array or matrix as argument


arr = np.matrix([[1,2,3,33],
                 [4,5,6,66],
                 [7,8,9,90]])

max_value = np.max(arr)
print('Maximum value',max_value)
min_value= np.min(arr)
print('Min value', min_value)


Maximum value 6600
Min value 1


In [36]:
# Find the number of rows and columns of a given matrix using NumPy

# we can find the rows and column number using shape function
# In the NumPy with the help of shape() function, we can find the number of rows and columns. In this function, 
# we pass a matrix and it will return row and column number of the matrix.

shape_of_arr= arr.shape
print('shape of array',shape_of_arr)

shape of array (3, 4)


In [43]:
#  Adding and Subtracting Matrices in Python

# Suppose we have two matrices A and B.
A = [[1,2],[3,4]]
B = [[4,5],[6,7]]

# then we get
# A+B = [[5,7],[9,11]]
# A-B = [[-3,-3],[-3,-3]]
print('we can add two matrix: ')
print(A+B)
print('we can subtract two matrix: ')
# print(A-B)

we can add two matrix: 
[[1, 2], [3, 4], [4, 5], [6, 7]]
we can subtract two matrix: 


In [21]:
# we can add and subtract element in a mtrix 
# importing numpy as np
import numpy as np


# creating first matrix
A = np.array([[1, 2], [3, 4]])

# creating second matrix
B = np.array([[4, 5], [6, 7]])

print("Printing elements of first matrix")
# print(A)
print("Printing elements of second matrix")
# print(B)

# adding two matrix
print("Addition of two matrix")
# print(np.add(A, B))

print("SUbtract of two matrix")

# print(np.subtract(A,B))


# Matrix Multiplication in NumPy
# print(np.dot(A,B))

#   multiplication using @ in numpy 

# print(A@B)


 #  Ways to add row/columns in numpy array
    

#  way to add row and columns using numpy
#  add columns-
#  1. np.append()
#  2. np.concatenate()
#  3. np.insert()
#  4. np.hstack()
#  5. np.column_stack()
 
#  adding rows method-
#  1. np.r_
#  2. np.insert()
#  3. np.append()
#  4. np.vstack()
 
# print('Before adding:',A)
column_need_be_added=np.array([[100],[200]])
new_arr=np.append(A,column_need_be_added,axis=1)
# print('new array:')
# print(new_arr)

# adding rows 

row_need_to_add= np.array([6,5])
new_matrix=np.r_[A,[row_need_to_add]]
# print(new_matrix)


# Finding the eigen values from a matrix 

eg= np.linalg.eigvals(A)

# print(eg)



Printing elements of first matrix
Printing elements of second matrix
Addition of two matrix
SUbtract of two matrix
Before adding: [[1 2]
 [3 4]]
[-0.37228132  5.37228132]


In [5]:
import numpy as np

# how to count the frequency of unique values in numpy array
number_list = np.array([1, 1, 2, 3, 4, 4, 1])
(unique, counts) = np.unique(number_list, return_counts=True)
# print(unique,  counts)
unique_count=len(np.unique(number_list))
# print(unique_count)

#  How to Calculate the determinant of a matrix using NumPy?
# creating a 2X2 Numpy matrix
n_array = np.array([[50, 29], [30, 44]])
det= np.linalg.det(n_array)
# print(det)

# Convert covariance matrix to correlation matrix using Python


1330.0000000000002
